name: learn-github-actions
on: [bush]
jobs:
        check-bats-version:
          runs-on: ubuntu-lastest
          steps:
              - uses: actions/checkout@v2
              - uses: action/setup-node@v1
              - run: npm install -g bats
              - run: bats -v
