name: Docker Hub description
on: [push]
jobs:
  docker-readme:
    runs-on: Ubuntu-20.04
    steps:
      - name: docker-readme
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD}}
          DOCKERHUB_REPOSITORY: tiktzuki/mysql